version: "3.8"

services:
  frontend:
    container_name: sw-service-app-frontend
    build:
      context: .
    volumes:
      - ./app
      - /app/node_modules     
    ports:
      - 80:4200
    stdin_open: true
    tty: true
    networks:
      - sw-network

networks:
  sw-network:
    driver: bridge

volumes:
  db: