name: Deploy to Host in Hostinger

on: [push]

jobs:
  trigger-build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /root
            ./fe_setup.sh
